name: photo_music_playlist
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2021.5.25=hecd8cb5_1
  - certifi=2021.5.30=py37hecd8cb5_0
  - intel-openmp=2021.2.0=hecd8cb5_564
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - mkl=2021.2.0=hecd8cb5_269
  - mkl-service=2.3.0=py37h9ed2024_1
  - mkl_fft=1.3.0=py37h4a7008c_2
  - mkl_random=1.2.1=py37hb2f4e1b_2
  - ncurses=6.2=h0a44026_1
  - numpy=1.20.2=py37h4b4dc7a_0
  - numpy-base=1.20.2=py37he0bd621_0
  - openssl=1.1.1k=h9ed2024_0
  - pandas=1.2.4=py37h23ab428_0
  - pip=21.1.2=py37hecd8cb5_0
  - python=3.7.10=h88f2d9e_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - readline=8.1=h9ed2024_0
  - setuptools=52.0.0=py37hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.35.4=hce871da_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - chardet==4.0.0
    - cycler==0.10.0
    - decorator==4.4.2
    - flickrapi==2.4.0
    - idna==2.10
    - imageio==2.9.0
    - kiwisolver==1.3.1
    - matplotlib==3.4.2
    - networkx==2.5.1
    - oauthlib==3.1.1
    - pillow==8.2.0
    - pyparsing==2.4.7
    - pywavelets==1.1.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - scikit-image==0.18.1
    - scipy==1.6.3
    - tifffile==2021.6.14
    - urllib3==1.26.5
